// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kaiqqoiymtbwixjyship.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthaXFxb2l5bXRid2l4anlzaGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjIyMjgsImV4cCI6MjA2OTk5ODIyOH0.Qb1zrQdAh7-lR0NNrbf2Mt1fpGkZlAlbAWa0PZVpJhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});